name: CI Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Run your script
      - name: Run hello.py
        run: python hello.py

      # Step 4: Install OpenAI library
      - name: Install OpenAI
        run: pip install --upgrade openai

      # Step 5: Verify OpenAI API key
      - name: Verify OpenAI secret
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python - <<'EOF'
          import os
          key = os.environ.get("OPENAI_API_KEY")
          if key:
              print("OpenAI API key is present ✔")
          else:
              raise ValueError("OPENAI_API_KEY is missing!")
          EOF


