name: CI Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Run hello.py (your existing script)
      - name: Run hello.py
        run: python hello.py

      # Step 4: Install OpenAI library
      - name: Install OpenAI
        run: pip install --upgrade openai

      # Step 5: Run hello_openai.py to verify secret and call OpenAI
      - name: Run OpenAI demo
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python hello_openai.py
